pipeline{
    agent any

    environment {
        // 配置 Git 仓库地址
        GIT_REPO = 'https://github.com/M-500/small-yello-book.git'
        // 配置 Harbor 仓库信息
        HARBOR_URL = '124.223.67.129:8081'
        HARBOR_PROJECT = 'ybook'
        IMAGE_NAME = 'gin-single-app'
        // Docker 镜像的标签
        TAG = "v1.0.1"
        // Docker 用户名和密码（可以通过 Jenkins 凭据管理）
        DOCKER_USER = 'wulinlin'
        DOCKER_PASS = 'Wll987055897'
        // 远程服务器 SSH 配置
    }
    stages{
        stage("拉取代码"){
            steps {
                echo '拉取成功'
                sh "ls -al"
            }
        }
        stage("执行构建"){
            steps {
                echo '开始构建'
                sh 'cd gin-svc && docker build .  -t ${HARBOR_PROJECT}/${IMAGE_NAME}:${TAG}'
                sh 'docker tag ${HARBOR_PROJECT}/${IMAGE_NAME}:${TAG} ${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:${TAG}'
                echo "构建成功"
            }
        }
        stage("发送image镜像到测试服务器"){
            steps {
                // 登录到 Harbor
                sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} ${HARBOR_URL}"

                // 推送镜像到 Harbor 仓库
                sh "docker push ${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:${TAG}"

                // 退出 Docker 登录
                sh "docker logout ${HARBOR_URL}"
            }
        }
//         stage("停止旧容器"){
//             steps {
//                 sh 'ssh -o Port=6000 linlin@124.223.67.129 "docker ps "'
//                 sh 'ssh -o Port=6000 linlin@124.223.67.129 "container_id = docker ps -q --filter "name = ybook_sever_test" "' //$(docker ps -q --filter "name=promptbio_backend_test")
//                 sh 'ssh -o Port=6000 linlin@124.223.67.129 "docker rm -f ${container_id}"'
//             }
//         }
        stage("拉取新镜像"){
             steps {
                 sh 'ssh -o Port=6000 linlin@124.223.67.129 "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} ${HARBOR_URL} "'
                 sh 'ssh -o Port=6000 linlin@124.223.67.129 "docker pull ${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:${TAG} "'
             }
         }
         stage("启动新容器"){
              steps {
                  sh 'ssh -o Port=6000 linlin@124.223.67.129 "docker run -d -p 8023:8023 --name ybook_sever_test ${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:${TAG}"'
              }
          }
    }
    post{
        always{
            echo 'always say goodbay'
            sh "docker rmi ${HARBOR_URL}/${HARBOR_PROJECT}/${IMAGE_NAME}:${TAG} || true"
        }
    }
}
