// Code generated by MockGen. DO NOT EDIT.
// Source: gin-svc/internal/repo (interfaces: VerificationCodeRepo)
//
// Generated by this command:
//
//	mockgen -destination=../repo/mocks/mock_verification_code_repo.go -package=mocks gin-svc/internal/repo VerificationCodeRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVerificationCodeRepo is a mock of VerificationCodeRepo interface.
type MockVerificationCodeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationCodeRepoMockRecorder
}

// MockVerificationCodeRepoMockRecorder is the mock recorder for MockVerificationCodeRepo.
type MockVerificationCodeRepoMockRecorder struct {
	mock *MockVerificationCodeRepo
}

// NewMockVerificationCodeRepo creates a new mock instance.
func NewMockVerificationCodeRepo(ctrl *gomock.Controller) *MockVerificationCodeRepo {
	mock := &MockVerificationCodeRepo{ctrl: ctrl}
	mock.recorder = &MockVerificationCodeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationCodeRepo) EXPECT() *MockVerificationCodeRepoMockRecorder {
	return m.recorder
}

// DeleteVerificationCode mocks base method.
func (m *MockVerificationCodeRepo) DeleteVerificationCode(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVerificationCode", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVerificationCode indicates an expected call of DeleteVerificationCode.
func (mr *MockVerificationCodeRepoMockRecorder) DeleteVerificationCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVerificationCode", reflect.TypeOf((*MockVerificationCodeRepo)(nil).DeleteVerificationCode), arg0, arg1)
}

// GetVerificationCode mocks base method.
func (m *MockVerificationCodeRepo) GetVerificationCode(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationCode", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerificationCode indicates an expected call of GetVerificationCode.
func (mr *MockVerificationCodeRepoMockRecorder) GetVerificationCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationCode", reflect.TypeOf((*MockVerificationCodeRepo)(nil).GetVerificationCode), arg0, arg1)
}

// SetVerificationCode mocks base method.
func (m *MockVerificationCodeRepo) SetVerificationCode(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVerificationCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVerificationCode indicates an expected call of SetVerificationCode.
func (mr *MockVerificationCodeRepoMockRecorder) SetVerificationCode(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerificationCode", reflect.TypeOf((*MockVerificationCodeRepo)(nil).SetVerificationCode), arg0, arg1, arg2)
}
