database:
  dsn: "root:root@tcp(127.0.0.1:13317)/y_book?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conn: 10  # 最大空闲连接数
  max_open_conn: 10  # 最大连接数

redis:
  addr: "127.0.0.1"
  port: 16379
  db: 1
  password: ""
