// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/na/email/send": {
            "post": {
                "description": "发送邮件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公共模块"
                ],
                "summary": "发送邮件",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.EmailForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/na/login": {
            "post": {
                "description": "邮箱登录/注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公共模块"
                ],
                "summary": "邮箱登录/注册",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.EmailLoginForm"
                        }
                    }
                ],
                "responses": {
                    "10011": {
                        "description": "登陆失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.LoginResp"
                        }
                    }
                }
            }
        },
        "/api/v1/roles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取角色列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色模块"
                ],
                "summary": "获取角色列表",
                "parameters": [
                    {
                        "description": "RolePageListReq",
                        "name": "use",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RolePageListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Role"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ginx.JsonResult"
                        }
                    }
                }
            },
            "put": {
                "description": "更新角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色模块"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "description": "UpdateRoleReq",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginx.JsonResult"
                        }
                    }
                }
            },
            "post": {
                "description": "创建角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色模块"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "CreateRoleReq",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginx.JsonResult"
                        }
                    }
                }
            }
        },
        "/api/v1/roles/{id}": {
            "get": {
                "description": "查询角色详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色模块"
                ],
                "summary": "查询角色详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.RoleDetail"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色模块"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginx.JsonResult"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "put": {
                "description": "更新用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UserForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "delete": {
                "description": "删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Permission": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mark": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "perKey": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.Role": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "roleKey": {
                    "type": "string"
                },
                "roleName": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "domain.RoleDetail": {
            "type": "object",
            "properties": {
                "perList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Permission"
                    }
                },
                "roleBase": {
                    "$ref": "#/definitions/domain.Role"
                }
            }
        },
        "ginx.JsonResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.LoginResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "types.CreateRoleReq": {
            "type": "object",
            "required": [
                "roleKey",
                "roleName",
                "status"
            ],
            "properties": {
                "perIds": {
                    "description": "权限ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "roleKey": {
                    "description": "角色key",
                    "type": "string"
                },
                "roleName": {
                    "description": "角色名",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "角色状态",
                    "type": "boolean"
                }
            }
        },
        "types.EmailForm": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "type_code": {
                    "description": "用来表示发送邮件的类型 1:注册 2:找回密码",
                    "type": "integer"
                }
            }
        },
        "types.EmailLoginForm": {
            "type": "object",
            "required": [
                "email",
                "ver_code"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "ver_code": {
                    "type": "string"
                }
            }
        },
        "types.RolePageListReq": {
            "type": "object",
            "properties": {
                "keywords": {
                    "description": "搜索关键词: 角色名，角色key，用于模糊搜索",
                    "type": "string"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "size": {
                    "description": "页大小",
                    "type": "integer"
                },
                "status": {
                    "description": "角色状态",
                    "type": "boolean"
                }
            }
        },
        "types.UpdateRoleReq": {
            "type": "object",
            "required": [
                "id",
                "roleName"
            ],
            "properties": {
                "id": {
                    "description": "角色ID",
                    "type": "integer"
                },
                "perIds": {
                    "description": "权限ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "roleName": {
                    "description": "角色名",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "角色状态",
                    "type": "boolean"
                }
            }
        },
        "types.UserForm": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "birthDay": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "male": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "profession": {
                    "type": "string"
                },
                "school": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger YBOOK API",
	Description:      "This is a sample Server pets",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
