definitions:
  types.LoginForm:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  types.UserForm:
    properties:
      addr:
        type: string
      avatar:
        type: string
      birthDay:
        type: string
      male:
        type: string
      nick_name:
        type: string
      password:
        type: string
      phone:
        type: string
      profession:
        type: string
      school:
        type: string
      signature:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/na/login:
    post:
      consumes:
      - application/json
      description: LoginCtl
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: LoginCtl
      tags:
      - NA Model
  /api/v1/na/register:
    post:
      consumes:
      - application/json
      description: RegisterUser
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.UserForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: RegisterUser
      tags:
      - NA Model
  /api/v1/users:
    put:
      consumes:
      - application/json
      description: Update user info
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.UserForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update user info
      tags:
      - User Model
  /api/v1/users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete user
      tags:
      - User Model
swagger: "2.0"
